import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.scanner': 'Scanner',
    'nav.solutions': 'Solutions',
    'nav.history': 'History',
    'nav.portalLogin': 'Portal Login',
    'nav.brand': 'SmartFarm AI',

    // Hero
    'hero.badge': 'AI-Powered Agriculture',
    'hero.title': 'Protect Your {0} with Intelligent Detection',
    'hero.titleHighlight': 'Harvest',
    'hero.subtitle': 'Instantly identify crop diseases, get treatment solutions, and maximize your yield with our advanced AI scanner.',
    'hero.launchScanner': 'Launch Scanner',
    'hero.exploreSolutions': 'Explore Solutions',
    'hero.liveDetection': 'Live Detection',
    'hero.detected': 'Detected',
    'hero.confidence': 'Confidence',
    'hero.scansCompleted': 'Scans Completed',
    'hero.accuracyRate': 'Accuracy Rate',
    'hero.diseasesDetected': 'Diseases Detected',
    'hero.farmersHelped': 'Farmers Helped',

    // Features
    'features.title': 'Why SmartFarm AI?',
    'features.subtitle': 'Cutting-edge technology designed for modern agriculture.',
    'features.instantDetection.title': 'Instant Detection',
    'features.instantDetection.desc': 'Upload a photo and get disease identification in seconds with 98% accuracy.',
    'features.treatmentSolutions.title': 'Treatment Solutions',
    'features.treatmentSolutions.desc': 'Receive organic and chemical treatment recommendations tailored to each disease.',
    'features.trackHistory.title': 'Track History',
    'features.trackHistory.desc': 'Keep a record of all your scans and monitor crop health over time.',

    // CTA
    'cta.title': 'Ready to Protect Your Crops?',
    'cta.subtitle': 'Join thousands of farmers using AI to safeguard their harvest.',
    'cta.button': 'Start Scanning Now',

    // Login
    'login.brand': 'SmartFarm AI',
    'login.brandSubtitle': 'Your intelligent farming companion. Access your dashboard, track scans, and manage your farm.',
    'login.feature1': 'Real-time Analytics',
    'login.feature2': 'Scan History',
    'login.feature3': 'AI Recommendations',
    'login.signIn': 'Sign In',
    'login.signUp': 'Sign Up',
    'login.fullName': 'Full Name',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.createAccount': 'Create Account',
    'login.signInBtn': 'Sign In',
    'login.alreadyAccount': 'Already have an account?',
    'login.noAccount': "Don't have an account?",
    'login.selectLanguage': 'Select Your Language',
    'login.languageSubtitle': 'Choose your preferred language to continue',
    'login.english': 'English',
    'login.hindi': 'हिन्दी',
    'login.gujarati': 'ગુજરાતી',
    'login.continue': 'Continue',

    // Scanner
    'scanner.title': 'AI Disease Scanner',
    'scanner.subtitle': 'Upload a photo of your crop leaf and let our AI identify diseases instantly.',
    'scanner.dropText': 'Click to upload or drag and drop',
    'scanner.dropHint': 'PNG, JPG or WEBP (max 10MB)',
    'scanner.changeImage': 'Change Image',
    'scanner.detectBtn': 'Detect Disease',
    'scanner.analyzing': 'Analyzing...',
    'scanner.analyzingText': 'Analyzing your crop image...',

    // ResultCard
    'result.title': 'Detection Result',
    'result.badge': 'AI Generated',
    'result.disease': 'Disease',
    'result.confidence': 'Confidence',
    'result.treatment': 'Treatment',
    'result.prevention': 'Prevention',
    'result.newScan': 'New Scan',
    'result.learnMore': 'Learn More',

    // Footer
    'footer.brand': '🌿 SmartFarm AI',
    'footer.brandDesc': 'Empowering farmers with AI-driven crop disease detection and smart agricultural solutions.',
    'footer.quickLinks': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.faq': 'FAQ',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.newsletter': 'Stay Updated',
    'footer.newsletterDesc': 'Get the latest in smart farming.',
    'footer.subscribe': 'Subscribe',
    'footer.copyright': '© 2026 SmartFarm AI. All rights reserved.',

    // Dashboard
    'dashboard.welcome': 'Welcome back, Farmer! 👋',
    'dashboard.subtitle': "Here's your farm health overview.",
    'dashboard.newScan': 'New Scan',
    'dashboard.totalScans': 'Total Scans',
    'dashboard.treated': 'Treated',
    'dashboard.pending': 'Pending',
    'dashboard.monitoring': 'Monitoring',
    'dashboard.recentScans': 'Recent Scans',
    'dashboard.viewAll': 'View All',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.scanCrops': 'Scan Crops',
    'dashboard.findSolutions': 'Find Solutions',
    'dashboard.viewHistory': 'View History',
    'dashboard.contactExpert': 'Contact Expert',

    // History
    'history.title': 'Scan History',
    'history.subtitle': 'Track all your crop disease detection records.',
    'history.filterAll': 'All',
    'history.filterTreated': 'Treated',
    'history.filterPending': 'Pending',
    'history.filterMonitoring': 'Monitoring',
    'history.filterHealthy': 'Healthy',
    'history.emptyTitle': 'No records found',
    'history.emptyDesc': 'Start scanning your crops to build your history.',
    'history.goScanner': 'Go to Scanner',
    'history.date': 'Date',
    'history.crop': 'Crop',
    'history.disease': 'Disease',
    'history.confidence': 'Confidence',
    'history.status': 'Status',
    'history.action': 'Action',
    'history.viewSolution': 'View Solution',

    // Solutions
    'solutions.title': 'Disease Solutions',
    'solutions.subtitle': 'Comprehensive database of crop diseases, treatments, and prevention methods.',
    'solutions.searchPlaceholder': 'Search diseases or crops...',
    'solutions.allCrops': 'All Crops',
    'solutions.emptyTitle': 'No diseases found',
    'solutions.emptyDesc': 'Try a different search term.',
    'solutions.symptoms': 'Symptoms',
    'solutions.treatment': 'Treatment',
    'solutions.prevention': 'Prevention',
    'solutions.viewDetails': 'View Full Details →',

    // SolutionDetail
    'detail.backToSolutions': '← Back to Solutions',
    'detail.symptoms': '📋 Symptoms',
    'detail.causes': '🔬 Causes',
    'detail.chemicalTreatment': '💊 Chemical Treatment',
    'detail.organicTreatment': '🌿 Organic Treatment',
    'detail.prevention': '🛡️ Prevention',
    'detail.recommendedTreatment': '⚕️ Recommended Treatment',
    'detail.cta': 'Detected this disease in your crops?',
    'detail.scanNow': 'Scan Your Crop Now',
    'detail.notFound': 'Disease not found',

    // Severity
    'severity.high': 'High',
    'severity.critical': 'Critical',
    'severity.medium': 'Medium',

    // Disease data
    'detail.affects': 'Affects:',

    'disease.1.name': 'Early Blight',
    'disease.1.crop': 'Tomato, Potato',
    'disease.1.symptoms': 'Dark spots with concentric rings on leaves, yellowing of surrounding tissue, defoliation in severe cases.',
    'disease.1.treatment': 'Apply Chlorothalonil or Mancozeb spray every 7-10 days. Use copper-based fungicides as an organic alternative.',
    'disease.1.prevention': 'Practice crop rotation with non-solanaceous crops. Avoid overhead irrigation. Use disease-free seeds and resistant varieties. Ensure proper plant spacing for air circulation.',
    'disease.1.causes': 'Fungus Alternaria solani, thrives in warm humid conditions with temperatures 24-30°C.',
    'disease.1.organic': 'Neem oil spray (5ml/L), baking soda solution (1tsp/L), copper fungicide.',
    'disease.1.chemical': 'Chlorothalonil, Mancozeb, Azoxystrobin. Apply at first sign of symptoms.',
    'disease.1.category': 'Fungal',

    'disease.2.name': 'Late Blight',
    'disease.2.crop': 'Potato, Tomato',
    'disease.2.symptoms': 'Water-soaked lesions on leaves, stems and fruits. White cottony fungal growth on leaf undersides in wet conditions. Rapid browning and collapse of foliage.',
    'disease.2.treatment': 'Remove and destroy infected plants immediately. Apply copper-based fungicides. Use metalaxyl + mancozeb for severe infections.',
    'disease.2.prevention': 'Plant resistant varieties. Ensure proper drainage. Avoid dense planting. Destroy volunteer plants and cull piles. Use certified disease-free seed potatoes.',
    'disease.2.causes': 'Oomycete Phytophthora infestans, spreads rapidly in cool wet weather (10-20°C, >90% humidity).',
    'disease.2.organic': 'Copper oxychloride spray, Bordeaux mixture.',
    'disease.2.chemical': 'Metalaxyl, Dimethomorph, Cymoxanil + Mancozeb.',
    'disease.2.category': 'Fungal',

    'disease.3.name': 'Leaf Blast',
    'disease.3.crop': 'Rice',
    'disease.3.symptoms': 'Diamond-shaped lesions with grey centers and dark brown borders on leaves. Lesions may coalesce causing leaf death. Neck blast causes panicle breakage.',
    'disease.3.treatment': 'Apply Tricyclazole or Carbendazim at early symptom appearance. Use Edifenphos for neck blast control.',
    'disease.3.prevention': 'Avoid excessive nitrogen fertilization. Maintain optimal water levels. Plant resistant varieties. Treat seeds with fungicides before sowing.',
    'disease.3.causes': 'Fungus Magnaporthe oryzae (Pyricularia oryzae), favored by high humidity, leaf wetness, and nitrogen-rich soils.',
    'disease.3.organic': 'Neem cake soil application, Trichoderma bio-control agent.',
    'disease.3.chemical': 'Tricyclazole, Carbendazim, Edifenphos, Isoprothiolane.',
    'disease.3.category': 'Fungal',

    'disease.4.name': 'Rust',
    'disease.4.crop': 'Wheat, Barley',
    'disease.4.symptoms': 'Small rust-colored pustules (uredinia) on leaves and stems. Pustules turn black (telia) at season end. Severely affected leaves dry up prematurely.',
    'disease.4.treatment': 'Apply Propiconazole or Tebuconazole at first sign. Mancozeb provides protective coverage.',
    'disease.4.prevention': 'Grow resistant varieties. Early sowing reduces exposure. Avoid excessive nitrogen. Remove volunteer wheat plants. Foliar fungicide at flag leaf stage.',
    'disease.4.causes': 'Fungus Puccinia spp. (P. triticina for leaf rust, P. graminis for stem rust). Uredospores spread by wind.',
    'disease.4.organic': 'Sulfur spray, Bacillus subtilis bio-fungicide.',
    'disease.4.chemical': 'Propiconazole, Tebuconazole, Mancozeb, Azoxystrobin.',
    'disease.4.category': 'Fungal',

    'disease.5.name': 'Bacterial Blight',
    'disease.5.crop': 'Rice, Cotton',
    'disease.5.symptoms': 'Water-soaked lesions on leaves turning yellow to brown with wavy margins. Bacterial ooze appears on young lesions in morning. Severe infection causes wilting.',
    'disease.5.treatment': 'Use copper oxychloride spray. Streptomycin seed treatment. Drain fields and reduce nitrogen.',
    'disease.5.prevention': 'Use certified disease-free seeds. Avoid flood irrigation. Plant resistant varieties. Balanced fertilization. Field sanitation.',
    'disease.5.causes': 'Bacterium Xanthomonas oryzae pv. oryzae (rice) / Xanthomonas campestris pv. malvacearum (cotton). Enters through wounds/hydathodes.',
    'disease.5.organic': 'Copper oxychloride spray, Pseudomonas fluorescens bio-control.',
    'disease.5.chemical': 'Streptomycin sulfate, Copper oxychloride, Bordeaux mixture.',
    'disease.5.category': 'Bacterial',

    'disease.6.name': 'Powdery Mildew',
    'disease.6.crop': 'Cucurbits, Grapes',
    'disease.6.symptoms': 'White to gray powdery fungal growth on upper leaf surfaces, stems, and fruits. Leaves become distorted and yellow. Reduced photosynthesis.',
    'disease.6.treatment': 'Apply sulfur-based fungicides or potassium bicarbonate. Use neem oil for mild infections. Systemic fungicides for severe cases.',
    'disease.6.prevention': 'Ensure good air circulation. Avoid overhead watering. Plant in full sun. Resistant varieties available for many crops. Proper trellising.',
    'disease.6.causes': 'Fungus Erysiphe spp. (cucurbits) / Uncinula necator (grapes). Favor moderate temps (15-27°C) and high humidity but not rainfall.',
    'disease.6.organic': 'Sulfur dust/spray, Neem oil, Potassium bicarbonate, Milk spray (1:9 ratio).',
    'disease.6.chemical': 'Myclobutanil, Propiconazole, Trifloxystrobin, Sulfur.',
    'disease.6.category': 'Fungal',

    'disease.7.name': 'Leaf Spot',
    'disease.7.crop': 'Groundnut, Soybean',
    'disease.7.symptoms': 'Brown to dark circular spots with yellow halos on leaves. Spots coalesce causing leaf blighting and premature defoliation.',
    'disease.7.treatment': 'Apply Carbendazim + Mancozeb combination spray. Chlorothalonil provides effective control.',
    'disease.7.prevention': 'Crop rotation with non-legumes. Use resistant varieties. Field sanitation - remove crop debris. Treat seeds with fungicides.',
    'disease.7.causes': 'Cercospora spp. (early leaf spot) / Phaeoisariopsis personata (late leaf spot). Spread by wind and rain splash.',
    'disease.7.organic': 'Neem oil spray, Trichoderma viride bio-control agent.',
    'disease.7.chemical': 'Carbendazim, Mancozeb, Chlorothalonil, Tebuconazole.',
    'disease.7.category': 'Fungal',

    'disease.8.name': 'Downy Mildew',
    'disease.8.crop': 'Grapes, Cucurbits',
    'disease.8.symptoms': 'Yellow angular spots on upper leaf surface. Purple-gray fuzzy growth on undersides. Infected shoots become stunted and distorted.',
    'disease.8.treatment': 'Apply Metalaxyl + Mancozeb or Fosetyl-Al. Remove and destroy infected leaves. Preventive spraying critical before infection.',
    'disease.8.prevention': 'Avoid leaf wetness - use drip irrigation. Proper trellising for air movement. Plant resistant varieties. Apply preventive fungicides during wet periods.',
    'disease.8.causes': 'Oomycete Plasmopara viticola (grapes) / Pseudoperonospora cubensis (cucurbits). Needs free water on leaves for infection.',
    'disease.8.organic': 'Copper oxychloride, Bordeaux mixture, Potassium phosphite.',
    'disease.8.chemical': 'Metalaxyl, Mancozeb, Fosetyl-Al, Dimethomorph, Cymoxanil.',
    'disease.8.category': 'Fungal',

    'disease.9.name': 'Anthracnose',
    'disease.9.crop': 'Chilli, Mango',
    'disease.9.symptoms': 'Sunken dark lesions on fruits with pinkish spore masses. Leaf spots are irregular brown areas. Fruit rot in storage.',
    'disease.9.treatment': 'Apply Copper oxychloride or Carbendazim spray. Remove and destroy infected fruits. Post-harvest hot water treatment for mangoes.',
    'disease.9.prevention': 'Prune affected branches. Proper orchard sanitation. Avoid overhead irrigation. Apply protective fungicide during flowering.',
    'disease.9.causes': 'Colletotrichum spp. (C. capsici for chilli, C. gloeosporioides for mango). Spread by rain splash, survives on plant debris.',
    'disease.9.organic': 'Copper oxychloride, Neem oil, Trichoderma harzianum.',
    'disease.9.chemical': 'Carbendazim, Mancozeb, Chlorothalonil, Azoxystrobin.',
    'disease.9.category': 'Fungal',

    'disease.10.name': 'Wilt',
    'disease.10.crop': 'Tomato, Brinjal',
    'disease.10.symptoms': 'Wilting of leaves, vascular discoloration in stem.',
    'disease.10.treatment': 'Soil drench with Carbendazim, remove infected plants.',
    'disease.10.prevention': 'Soil solarization, resistant rootstocks, crop rotation.',
    'disease.10.causes': 'Fungal or bacterial pathogens in soil, enters through roots.',
    'disease.10.organic': 'Neem cake soil application, Trichoderma bio-control.',
    'disease.10.chemical': 'Carbendazim soil drench, Copper oxychloride.',
    'disease.10.category': 'Fungal',

    // NotFound
    'notFound.title': 'Page Not Found',
    'notFound.desc': "Oops! The page you're looking for doesn't exist.",
    'notFound.button': 'Return Home',
  },

  hi: {
    'nav.home': 'होम',
    'nav.scanner': 'स्कैनर',
    'nav.solutions': 'समाधान',
    'nav.history': 'इतिहास',
    'nav.portalLogin': 'पोर्टल लॉगिन',
    'nav.brand': 'स्मार्टफार्म AI',

    'hero.badge': 'AI-संचालित कृषि',
    'hero.title': 'बुद्धिमान जांच से अपनी {0} की रक्षा करें',
    'hero.titleHighlight': 'फसल',
    'hero.subtitle': 'हमारे उन्नत AI स्कैनर से फसल रोगों की तुरंत पहचान करें, उपचार समाधान प्राप्त करें और अपनी पैदावार बढ़ाएं।',
    'hero.launchScanner': 'स्कैनर चलाएं',
    'hero.exploreSolutions': 'समाधान देखें',
    'hero.liveDetection': 'लाइव जांच',
    'hero.detected': 'पता चला',
    'hero.confidence': 'विश्वास स्तर',
    'hero.scansCompleted': 'स्कैन पूर्ण',
    'hero.accuracyRate': 'सटीकता दर',
    'hero.diseasesDetected': 'रोग पहचाने गए',
    'hero.farmersHelped': 'किसानों की मदद',

    'features.title': 'स्मार्टफार्म AI क्यों?',
    'features.subtitle': 'आधुनिक कृषि के लिए अत्याधुनिक तकनीक।',
    'features.instantDetection.title': 'तुरंत जांच',
    'features.instantDetection.desc': 'फोटो अपलोड करें और 98% सटीकता के साथ सेकंडों में रोग की पहचान पाएं।',
    'features.treatmentSolutions.title': 'उपचार समाधान',
    'features.treatmentSolutions.desc': 'प्रत्येक रोग के अनुरूप जैविक और रासायनिक उपचार सिफारिशें प्राप्त करें।',
    'features.trackHistory.title': 'इतिहास ट्रैक करें',
    'features.trackHistory.desc': 'अपने सभी स्कैन का रिकॉर्ड रखें और समय के साथ फसल स्वास्थ्य की निगरानी करें।',

    'cta.title': 'अपनी फसलों की रक्षा के लिए तैयार हैं?',
    'cta.subtitle': 'हजारों किसानों के साथ जुड़ें जो अपनी फसल की सुरक्षा के लिए AI का उपयोग कर रहे हैं।',
    'cta.button': 'अभी स्कैन करना शुरू करें',

    'login.brand': 'स्मार्टफार्म AI',
    'login.brandSubtitle': 'आपका बुद्धिमान कृषि साथी। अपने डैशबोर्ड तक पहुंचें, स्कैन ट्रैक करें और अपने फार्म का प्रबंधन करें।',
    'login.feature1': 'रीयल-टाइम एनालिटिक्स',
    'login.feature2': 'स्कैन इतिहास',
    'login.feature3': 'AI सिफारिशें',
    'login.signIn': 'साइन इन',
    'login.signUp': 'साइन अप',
    'login.fullName': 'पूरा नाम',
    'login.email': 'ईमेल पता',
    'login.password': 'पासवर्ड',
    'login.rememberMe': 'मुझे याद रखें',
    'login.forgotPassword': 'पासवर्ड भूल गए?',
    'login.createAccount': 'खाता बनाएं',
    'login.signInBtn': 'साइन इन',
    'login.alreadyAccount': 'पहले से खाता है?',
    'login.noAccount': 'खाता नहीं है?',
    'login.selectLanguage': 'अपनी भाषा चुनें',
    'login.languageSubtitle': 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें',
    'login.english': 'English',
    'login.hindi': 'हिन्दी',
    'login.gujarati': 'ગુજરાતી',
    'login.continue': 'जारी रखें',

    'scanner.title': 'AI रोग स्कैनर',
    'scanner.subtitle': 'अपनी फसल के पत्ते की फोटो अपलोड करें और हमारा AI तुरंत रोगों की पहचान करे।',
    'scanner.dropText': 'अपलोड करने के लिए क्लिक करें या खींचें और छोड़ें',
    'scanner.dropHint': 'PNG, JPG या WEBP (अधिकतम 10MB)',
    'scanner.changeImage': 'इमेज बदलें',
    'scanner.detectBtn': 'रोग का पता लगाएं',
    'scanner.analyzing': 'विश्लेषण कर रहा है...',
    'scanner.analyzingText': 'आपकी फसल की इमेज का विश्लेषण...',

    'result.title': 'जांच परिणाम',
    'result.badge': 'AI द्वारा उत्पन्न',
    'result.disease': 'रोग',
    'result.confidence': 'विश्वास स्तर',
    'result.treatment': 'उपचार',
    'result.prevention': 'रोकथाम',
    'result.newScan': 'नया स्कैन',
    'result.learnMore': 'और जानें',

    'footer.brand': '🌿 स्मार्टफार्म AI',
    'footer.brandDesc': 'AI-संचालित फसल रोग जांच और स्मार्ट कृषि समाधानों के साथ किसानों को सशक्त बनाना।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.resources': 'संसाधन',
    'footer.faq': 'FAQ',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.contact': 'संपर्क करें',
    'footer.newsletter': 'अपडेट रहें',
    'footer.newsletterDesc': 'स्मार्ट खेती की नवीनतम जानकारी प्राप्त करें।',
    'footer.subscribe': 'सदस्यता लें',
    'footer.copyright': '© 2026 स्मार्टफार्म AI। सर्वाधिकार सुरक्षित।',

    'dashboard.welcome': 'वापसी पर स्वागत है, किसान! 👋',
    'dashboard.subtitle': 'आपके फार्म स्वास्थ्य का अवलोकन।',
    'dashboard.newScan': 'नया स्कैन',
    'dashboard.totalScans': 'कुल स्कैन',
    'dashboard.treated': 'उपचारित',
    'dashboard.pending': 'लंबित',
    'dashboard.monitoring': 'निगरानी',
    'dashboard.recentScans': 'हाल के स्कैन',
    'dashboard.viewAll': 'सभी देखें',
    'dashboard.quickActions': 'त्वरित कार्रवाइयां',
    'dashboard.scanCrops': 'फसल स्कैन करें',
    'dashboard.findSolutions': 'समाधान खोजें',
    'dashboard.viewHistory': 'इतिहास देखें',
    'dashboard.contactExpert': 'विशेषज्ञ से संपर्क',

    'history.title': 'स्कैन इतिहास',
    'history.subtitle': 'अपने सभी फसल रोग जांच रिकॉर्ड ट्रैक करें।',
    'history.filterAll': 'सभी',
    'history.filterTreated': 'उपचारित',
    'history.filterPending': 'लंबित',
    'history.filterMonitoring': 'निगरानी',
    'history.filterHealthy': 'स्वस्थ',
    'history.emptyTitle': 'कोई रिकॉर्ड नहीं मिला',
    'history.emptyDesc': 'अपना इतिहास बनाने के लिए अपनी फसलों को स्कैन करना शुरू करें।',
    'history.goScanner': 'स्कैनर पर जाएं',
    'history.date': 'तारीख',
    'history.crop': 'फसल',
    'history.disease': 'रोग',
    'history.confidence': 'विश्वास',
    'history.status': 'स्थिति',
    'history.action': 'कार्रवाई',
    'history.viewSolution': 'समाधान देखें',

    'solutions.title': 'रोग समाधान',
    'solutions.subtitle': 'फसल रोगों, उपचारों और रोकथाम के तरीकों का व्यापक डेटाबेस।',
    'solutions.searchPlaceholder': 'रोग या फसल खोजें...',
    'solutions.allCrops': 'सभी फसलें',
    'solutions.emptyTitle': 'कोई रोग नहीं मिला',
    'solutions.emptyDesc': 'कोई अन्य खोज शब्द आज़माएं।',
    'solutions.symptoms': 'लक्षण',
    'solutions.treatment': 'उपचार',
    'solutions.prevention': 'रोकथाम',
    'solutions.viewDetails': 'पूर्ण विवरण देखें →',

    'detail.backToSolutions': '← समाधान पर वापस',
    'detail.symptoms': '📋 लक्षण',
    'detail.causes': '🔬 कारण',
    'detail.chemicalTreatment': '💊 रासायनिक उपचार',
    'detail.organicTreatment': '🌿 जैविक उपचार',
    'detail.prevention': '🛡️ रोकथाम',
    'detail.recommendedTreatment': '⚕️ अनुशंसित उपचार',
    'detail.cta': 'अपनी फसलों में यह रोग पाया?',
    'detail.scanNow': 'अपनी फसल अभी स्कैन करें',
    'detail.notFound': 'रोग नहीं मिला',

    // Severity
    'severity.high': 'उच्च',
    'severity.critical': 'गंभीर',
    'severity.medium': 'मध्यम',

    // Disease data
    'detail.affects': 'प्रभावित:',

    'disease.1.name': 'अर्ली ब्लाइट',
    'disease.1.crop': 'टमाटर, आलू',
    'disease.1.symptoms': 'पत्तियों पर संकेंद्रित छल्लों के साथ गहरे धब्बे, आसपास के ऊतकों का पीला पड़ना, गंभीर मामलों में पत्ती गिरना।',
    'disease.1.treatment': 'हर 7-10 दिन में क्लोरोथालोनिल या मैन्कोज़ेब स्प्रे करें। जैविक विकल्प के रूप में कॉपर-आधारित फफूंदनाशकों का उपयोग करें।',
    'disease.1.prevention': 'गैर-सोलेनेसियस फसलों के साथ फसल चक्र अपनाएं। ऊपरी सिंचाई से बचें। रोग-मुक्त बीज और प्रतिरोधी किस्मों का उपयोग करें।',
    'disease.1.causes': 'कवक अल्टरनेरिया सोलानी, 24-30°C तापमान वाली गर्म आर्द्र परिस्थितियों में पनपता है।',
    'disease.1.organic': 'नीम तेल स्प्रे (5ml/L), बेकिंग सोडा घोल (1 चम्मच/ली), कॉपर फफूंदनाशक।',
    'disease.1.chemical': 'क्लोरोथालोनिल, मैन्कोज़ेब, एज़ोक्सीस्ट्रोबिन। लक्षण दिखने पर लगाएं।',
    'disease.1.category': 'फंगल',

    'disease.2.name': 'लेट ब्लाइट',
    'disease.2.crop': 'आलू, टमाटर',
    'disease.2.symptoms': 'पत्तियों, तनों और फलों पर पानी से लथपथ घाव। गीली परिस्थितियों में पत्तियों के नीचे सफेद रुई जैसी फफूंद वृद्धि। तेजी से भूरापन और पत्तियों का गिरना।',
    'disease.2.treatment': 'संक्रमित पौधों को तुरंत हटाएं और नष्ट करें। कॉपर-आधारित फफूंदनाशक लगाएं। गंभीर संक्रमण के लिए मेटालैक्सिल + मैन्कोज़ेब का उपयोग करें।',
    'disease.2.prevention': 'प्रतिरोधी किस्में लगाएं। उचित जल निकासी सुनिश्चित करें। घने रोपण से बचें। प्रमाणित रोग-मुक्त बीज आलू का उपयोग करें।',
    'disease.2.causes': 'फाइटोफ्थोरा इन्फेस्टैंस, ठंडे गीले मौसम (10-20°C, >90% आर्द्रता) में तेजी से फैलता है।',
    'disease.2.organic': 'कॉपर ऑक्सीक्लोराइड स्प्रे, बोर्डो मिश्रण।',
    'disease.2.chemical': 'मेटालैक्सिल, डाइमेथोमॉर्फ, साइमॉक्सानिल + मैन्कोज़ेब।',
    'disease.2.category': 'फंगल',

    'disease.3.name': 'लीफ ब्लास्ट',
    'disease.3.crop': 'चावल',
    'disease.3.symptoms': 'पत्तियों पर भूरे केंद्र और गहरे भूरे किनारों वाले हीरे के आकार के घाव। घाव मिलकर पत्ती मृत्यु का कारण बन सकते हैं।',
    'disease.3.treatment': 'लक्षण दिखने पर ट्राइसाइक्लाज़ोल या कार्बेन्डाजिम लगाएं। नेक ब्लास्ट नियंत्रण के लिए एडिफेनफोस का उपयोग करें।',
    'disease.3.prevention': 'अत्यधिक नाइट्रोजन उर्वरक से बचें। इष्टतम जल स्तर बनाए रखें। प्रतिरोधी किस्में लगाएं। बुवाई से पहले बीजों को फफूंदनाशकों से उपचारित करें।',
    'disease.3.causes': 'कवक मैग्नापोर्थे ओराइजी, उच्च आर्द्रता, पत्ती की नमी और नाइट्रोजन युक्त मिट्टी द्वारा बढ़ावा।',
    'disease.3.organic': 'नीम खली मिट्टी अनुप्रयोग, ट्राइकोडर्मा जैव-नियंत्रक एजेंट।',
    'disease.3.chemical': 'ट्राइसाइक्लाज़ोल, कार्बेन्डाजिम, एडिफेनफोस, आइसोप्रोथियोलेन।',
    'disease.3.category': 'फंगल',

    'disease.4.name': 'रस्ट',
    'disease.4.crop': 'गेहूं, जौ',
    'disease.4.symptoms': 'पत्तियों और तनों पर छोटे जंग के रंग के फुंसी। मौसम के अंत में फुंसी काले हो जाते हैं। गंभीर रूप से प्रभावित पत्तियाँ समय से पहले सूख जाती हैं।',
    'disease.4.treatment': 'पहले संकेत पर प्रोपिकोनाज़ोल या टेबुकोनाज़ोल लगाएं। मैन्कोज़ेब सुरक्षात्मक कवरेज प्रदान करता है।',
    'disease.4.prevention': 'प्रतिरोधी किस्में उगाएं। जल्दी बुवाई से जोखिम कम होता है। अत्यधिक नाइट्रोजन से बचें। स्वयंसेवी गेहूं के पौधों को हटा दें।',
    'disease.4.causes': 'कवक पक्सिनिया एसपीपी, हवा द्वारा फैलने वाले यूरेडोस्पोर।',
    'disease.4.organic': 'सल्फर स्प्रे, बैसिलस सबटिलिस जैव-कवकनाशी।',
    'disease.4.chemical': 'प्रोपिकोनाज़ोल, टेबुकोनाज़ोल, मैन्कोज़ेब, एज़ोक्सीस्ट्रोबिन।',
    'disease.4.category': 'फंगल',

    'disease.5.name': 'बैक्टीरियल ब्लाइट',
    'disease.5.crop': 'चावल, कपास',
    'disease.5.symptoms': 'पत्तियों पर पानी से लथपथ घाव लहरदार किनारों के साथ पीले से भूरे हो जाते हैं। सुबह युवा घावों पर बैक्टीरियल रिसाव दिखाई देता है।',
    'disease.5.treatment': 'कॉपर ऑक्सीक्लोराइड स्प्रे का उपयोग करें। स्ट्रेप्टोमाइसिन बीज उपचार। खेतों से पानी निकालें और नाइट्रोजन कम करें।',
    'disease.5.prevention': 'प्रमाणित रोग-मुक्त बीजों का उपयोग करें। बाढ़ सिंचाई से बचें। प्रतिरोधी किस्में लगाएं। संतुलित उर्वरक। खेत की सफाई।',
    'disease.5.causes': 'जीवाणु जैन्थोमोनास ओराइजी, घावों/हाइडेथोड्स के माध्यम से प्रवेश करता है।',
    'disease.5.organic': 'कॉपर ऑक्सीक्लोराइड स्प्रे, स्यूडोमोनास फ्लोरेसेंस जैव-नियंत्रण।',
    'disease.5.chemical': 'स्ट्रेप्टोमाइसिन सल्फेट, कॉपर ऑक्सीक्लोराइड, बोर्डो मिश्रण।',
    'disease.5.category': 'बैक्टीरियल',

    'disease.6.name': 'पाउडरी मिल्ड्यू',
    'disease.6.crop': 'कुकुरबिट, अंगूर',
    'disease.6.symptoms': 'पत्तियों, तनों और फलों पर सफेद से भूरे रंग की पाउडर जैसी फफूंद वृद्धि। पत्तियाँ विकृत और पीली हो जाती हैं। प्रकाश संश्लेषण कम हो जाता है।',
    'disease.6.treatment': 'सल्फर-आधारित फफूंदनाशक या पोटैशियम बाइकार्बोनेट लगाएं। हल्के संक्रमण के लिए नीम तेल का उपयोग करें।',
    'disease.6.prevention': 'अच्छा वायु संचार सुनिश्चित करें। ऊपर से पानी देने से बचें। पूर्ण सूर्य में लगाएं। उचित ट्रेलिसिंग।',
    'disease.6.causes': 'कवक एरीसिफ़े एसपीपी (कुकुरबिट) / अनसिनुला नेकाटर (अंगूर)। मध्यम तापमान (15-27°C) और उच्च आर्द्रता पसंद करते हैं।',
    'disease.6.organic': 'सल्फर धूल/स्प्रे, नीम तेल, पोटैशियम बाइकार्बोनेट, दूध स्प्रे (1:9)।',
    'disease.6.chemical': 'माइक्लोब्यूटानिल, प्रोपिकोनाज़ोल, ट्राइफ्लोक्सीस्ट्रोबिन, सल्फर।',
    'disease.6.category': 'फंगल',

    'disease.7.name': 'लीफ स्पॉट',
    'disease.7.crop': 'मूंगफली, सोयाबीन',
    'disease.7.symptoms': 'पत्तियों पर पीले प्रभामंडल के साथ भूरे से गहरे गोलाकार धब्बे। धब्बे मिलकर पत्ती झुलसा और समय से पहले पत्ती गिरने का कारण बनते हैं।',
    'disease.7.treatment': 'कार्बेन्डाजिम + मैन्कोज़ेब संयोजन स्प्रे लगाएं। क्लोरोथालोनिल प्रभावी नियंत्रण प्रदान करता है।',
    'disease.7.prevention': 'गैर-फलीदार फसलों के साथ फसल चक्र। प्रतिरोधी किस्मों का उपयोग करें। फसल अवशेष हटाएं। बीजों को फफूंदनाशकों से उपचारित करें।',
    'disease.7.causes': 'सेरकोस्पोरा एसपीपी (प्रारंभिक) / फेयोइसारियोप्सिस पर्सनाटा (देर से)। हवा और बारिश के छींटे से फैलता है।',
    'disease.7.organic': 'नीम तेल स्प्रे, ट्राइकोडर्मा विरिडे जैव-नियंत्रक।',
    'disease.7.chemical': 'कार्बेन्डाजिम, मैन्कोज़ेब, क्लोरोथालोनिल, टेबुकोनाज़ोल।',
    'disease.7.category': 'फंगल',

    'disease.8.name': 'डाउनी मिल्ड्यू',
    'disease.8.crop': 'अंगूर, कुकुरबिट',
    'disease.8.symptoms': 'पत्तियों के ऊपरी भाग पर पीले कोणीय धब्बे। नीचे की ओर बैंगनी-भूरे रंग की रोईं जैसी वृद्धि। प्रभावित अंकुर बौने और विकृत हो जाते हैं।',
    'disease.8.treatment': 'मेटालैक्सिल + मैन्कोज़ेब या फोसेटाइल-एएल लगाएं। संक्रमित पत्तियों को हटाएं और नष्ट करें।',
    'disease.8.prevention': 'पत्तियों की नमी से बचें - ड्रिप सिंचाई का उपयोग करें। वायु संचार के लिए उचित ट्रेलिसिंग। प्रतिरोधी किस्में लगाएं।',
    'disease.8.causes': 'प्लास्मोपारा विटिकोला (अंगूर) / स्यूडोपेरोनोस्पोरा क्यूबेंसिस (कुकुरबिट)। संक्रमण के लिए पत्तियों पर मुक्त पानी की आवश्यकता होती है।',
    'disease.8.organic': 'कॉपर ऑक्सीक्लोराइड, बोर्डो मिश्रण, पोटैशियम फॉस्फाइट।',
    'disease.8.chemical': 'मेटालैक्सिल, मैन्कोज़ेब, फोसेटाइल-एएल, डाइमेथोमॉर्फ, साइमॉक्सानिल।',
    'disease.8.category': 'फंगल',

    'disease.9.name': 'एन्थ्रेक्नोज',
    'disease.9.crop': 'मिर्च, आम',
    'disease.9.symptoms': 'फलों पर गुलाबी बीजाणु द्रव्यमान के साथ धँसे हुए गहरे घाव। पत्ती के धब्बे अनियमित भूरे क्षेत्र हैं। भंडारण में फल सड़न।',
    'disease.9.treatment': 'कॉपर ऑक्सीक्लोराइड या कार्बेन्डाजिम स्प्रे लगाएं। संक्रमित फलों को हटाएं और नष्ट करें। आम के लिए कटाई के बाद गर्म पानी उपचार।',
    'disease.9.prevention': 'प्रभावित शाखाओं को काटें। उचित बगीचा स्वच्छता। ऊपरी सिंचाई से बचें। फूल आने के दौरान सुरक्षात्मक फफूंदनाशक लगाएं।',
    'disease.9.causes': 'कोलेटोट्राइकम एसपीपी। बारिश के छींटे से फैलता है, पौधे के मलबे पर जीवित रहता है।',
    'disease.9.organic': 'कॉपर ऑक्सीक्लोराइड, नीम तेल, ट्राइकोडर्मा हार्जियानम।',
    'disease.9.chemical': 'कार्बेन्डाजिम, मैन्कोज़ेब, क्लोरोथालोनिल, एज़ोक्सीस्ट्रोबिन।',
    'disease.9.category': 'फंगल',

    'disease.10.name': 'विल्ट',
    'disease.10.crop': 'टमाटर, बैंगन',
    'disease.10.symptoms': 'पत्तियों का मुरझाना, तने में संवहनी मलिनकिरण।',
    'disease.10.treatment': 'कार्बेन्डाजिम से मिट्टी को भिगोएं, संक्रमित पौधों को हटाएं।',
    'disease.10.prevention': 'मिट्टी सौरीकरण, प्रतिरोधी रूटस्टॉक, फसल चक्र।',
    'disease.10.causes': 'मिट्टी में फंगल या बैक्टीरियल रोगजनक, जड़ों के माध्यम से प्रवेश करते हैं।',
    'disease.10.organic': 'नीम खली मिट्टी अनुप्रयोग, ट्राइकोडर्मा जैव-नियंत्रण।',
    'disease.10.chemical': 'कार्बेन्डाजिम मृदा भिगोना, कॉपर ऑक्सीक्लोराइड।',
    'disease.10.category': 'फंगल',

    'notFound.title': 'पेज नहीं मिला',
    'notFound.desc': 'ओह! आप जिस पेज की तलाश कर रहे हैं वह मौजूद नहीं है।',
    'notFound.button': 'होम पेज पर वापस जाएं',
  },

  gu: {
    'nav.home': 'હોમ',
    'nav.scanner': 'સ્કેનર',
    'nav.solutions': 'સોલ્યુશન્સ',
    'nav.history': 'ઇતિહાસ',
    'nav.portalLogin': 'પોર્ટલ લૉગિન',
    'nav.brand': 'સ્માર્ટફાર્મ AI',

    'hero.badge': 'AI-સંચાલિત કૃષિ',
    'hero.title': 'બુદ્ધિશાળી તપાસથી તમારા {0}નું રક્ષણ કરો',
    'hero.titleHighlight': 'પાક',
    'hero.subtitle': 'અમારા અદ્યતન AI સ્કેનર વડે પાક રોગોને તરત ઓળખો, સારવાર ઉકેલો મેળવો અને તમારી ઉપજ વધારો.',
    'hero.launchScanner': 'સ્કેનર શરૂ કરો',
    'hero.exploreSolutions': 'સોલ્યુશન્સ એક્સપ્લોર કરો',
    'hero.liveDetection': 'લાઇવ તપાસ',
    'hero.detected': 'શોધાયું',
    'hero.confidence': 'વિશ્વાસ સ્તર',
    'hero.scansCompleted': 'સ્કેન પૂર્ણ',
    'hero.accuracyRate': 'ચોકસાઈ દર',
    'hero.diseasesDetected': 'રોગો શોધાયા',
    'hero.farmersHelped': 'ખેડૂતોને મદદ',
    'hero.leafBlight': 'પાન ફૂગ',

    'features.title': 'સ્માર્ટફાર્મ AI કેમ?',
    'features.subtitle': 'આધુનિક કૃષિ માટે અત્યાધુનિક ટેકનોલોજી.',
    'features.instantDetection.title': 'તાત્કાલિક તપાસ',
    'features.instantDetection.desc': 'ફોટો અપલોડ કરો અને 98% ચોકસાઈ સાથે સેકંડોમાં રોગની ઓળખ મેળવો.',
    'features.treatmentSolutions.title': 'સારવાર ઉકેલો',
    'features.treatmentSolutions.desc': 'દરેક રોગ માટે કાર્બનિક અને રાસાયણિક સારવાર ભલામણો મેળવો.',
    'features.trackHistory.title': 'ઇતિહાસ ટ્રૅક કરો',
    'features.trackHistory.desc': 'તમારા બધા સ્કેનનો રેકોર્ડ રાખો અને સમય જતાં પાક આરોગ્યનું નિરીક્ષણ કરો.',

    'cta.title': 'તમારા પાકોના રક્ષણ માટે તૈયાર છો?',
    'cta.subtitle': 'હજારો ખેડૂતો સાથે જોડાઓ જેઓ તેમના પાકની સુરક્ષા માટે AI નો ઉપયોગ કરે છે.',
    'cta.button': 'હમણાં સ્કેન કરવાનું શરૂ કરો',

    'login.brand': 'સ્માર્ટફાર્મ AI',
    'login.brandSubtitle': 'તમારો બુદ્ધિશાળી ખેતી સાથી. તમારા ડેશબોર્ડમાં પ્રવેશ કરો, સ્કેન ટ્રૅક કરો અને તમારા ફાર્મનું સંચાલન કરો.',
    'login.feature1': 'રીઅલ-ટાઇમ એનાલિટિક્સ',
    'login.feature2': 'સ્કેન ઇતિહાસ',
    'login.feature3': 'AI ભલામણો',
    'login.signIn': 'સાઇન ઇન',
    'login.signUp': 'સાઇન અપ',
    'login.fullName': 'પૂરું નામ',
    'login.email': 'ઇમેઇલ સરનામું',
    'login.password': 'પાસવર્ડ',
    'login.rememberMe': 'મને યાદ રાખો',
    'login.forgotPassword': 'પાસવર્ડ ભૂલી ગયા?',
    'login.createAccount': 'ખાતું બનાવો',
    'login.signInBtn': 'સાઇન ઇન',
    'login.alreadyAccount': 'પહેલેથી ખાતું છે?',
    'login.noAccount': 'ખાતું નથી?',
    'login.selectLanguage': 'તમારી ભાષા પસંદ કરો',
    'login.languageSubtitle': 'ચાલુ રાખવા માટે તમારી પસંદગીની ભાષા પસંદ કરો',
    'login.english': 'English',
    'login.hindi': 'हिन्दी',
    'login.gujarati': 'ગુજરાતી',
    'login.continue': 'ચાલુ રાખો',

    'scanner.title': 'AI રોગ સ્કેનર',
    'scanner.subtitle': 'તમારા પાકના પાંદડાનો ફોટો અપલોડ કરો અને અમારું AI તરત રોગો ઓળખે.',
    'scanner.dropText': 'અપલોડ કરવા ક્લિક કરો અથવા ખેંચો અને મૂકો',
    'scanner.dropHint': 'PNG, JPG અથવા WEBP (મહત્તમ 10MB)',
    'scanner.changeImage': 'ઇમેજ બદલો',
    'scanner.detectBtn': 'રોગ શોધો',
    'scanner.analyzing': 'વિશ્લેષણ કરે છે...',
    'scanner.analyzingText': 'તમારા પાકના ચિત્રનું વિશ્લેષણ...',

    'result.title': 'તપાસ પરિણામ',
    'result.badge': 'AI દ્વારા જનરેટેડ',
    'result.disease': 'રોગ',
    'result.confidence': 'વિશ્વાસ સ્તર',
    'result.treatment': 'સારવાર',
    'result.prevention': 'નિવારણ',
    'result.newScan': 'નવું સ્કેન',
    'result.learnMore': 'વધુ જાણો',

    'footer.brand': '🌿 સ્માર્ટફાર્મ AI',
    'footer.brandDesc': 'AI-સંચાલિત પાક રોગ તપાસ અને સ્માર્ટ કૃષિ ઉકેલો સાથે ખેડૂતોને સશક્ત બનાવવું.',
    'footer.quickLinks': 'ઝડપી લિંક્સ',
    'footer.resources': 'સંસાધનો',
    'footer.faq': 'FAQ',
    'footer.privacy': 'ગોપનીયતા નીતિ',
    'footer.terms': 'સેવાની શરતો',
    'footer.contact': 'સંપર્ક કરો',
    'footer.newsletter': 'અપડેટ રહો',
    'footer.newsletterDesc': 'સ્માર્ટ ખેતીની નવીનતમ માહિતી મેળવો.',
    'footer.subscribe': 'સબ્સ્ક્રાઇબ કરો',
    'footer.copyright': '© 2026 સ્માર્ટફાર્મ AI. બધા હકો અનામત.',

    'dashboard.welcome': 'પાછા આવકારો, ખેડૂત! 👋',
    'dashboard.subtitle': 'તમારા ફાર્મ આરોગ્યની ઝાંખી.',
    'dashboard.newScan': 'નવું સ્કેન',
    'dashboard.totalScans': 'કુલ સ્કેન',
    'dashboard.treated': 'સારવાર કરેલ',
    'dashboard.pending': 'બાકી',
    'dashboard.monitoring': 'નિરીક્ષણ',
    'dashboard.recentScans': 'તાજેતરના સ્કેન',
    'dashboard.viewAll': 'બધા જુઓ',
    'dashboard.quickActions': 'ઝડપી ક્રિયાઓ',
    'dashboard.scanCrops': 'પાક સ્કેન કરો',
    'dashboard.findSolutions': 'ઉકેલો શોધો',
    'dashboard.viewHistory': 'ઇતિહાસ જુઓ',
    'dashboard.contactExpert': 'નિષ્ણાતનો સંપર્ક કરો',

    'history.title': 'સ્કેન ઇતિહાસ',
    'history.subtitle': 'તમારા બધા પાક રોગ તપાસ રેકોર્ડ ટ્રૅક કરો.',
    'history.filterAll': 'બધા',
    'history.filterTreated': 'સારવાર કરેલ',
    'history.filterPending': 'બાકી',
    'history.filterMonitoring': 'નિરીક્ષણ',
    'history.filterHealthy': 'સ્વસ્થ',
    'history.emptyTitle': 'કોઈ રેકોર્ડ મળ્યો નથી',
    'history.emptyDesc': 'તમારો ઇતિહાસ બનાવવા તમારા પાકો સ્કેન કરવાનું શરૂ કરો.',
    'history.goScanner': 'સ્કેનર પર જાઓ',
    'history.date': 'તારીખ',
    'history.crop': 'પાક',
    'history.disease': 'રોગ',
    'history.confidence': 'વિશ્વાસ',
    'history.status': 'સ્થિતિ',
    'history.action': 'ક્રિયા',
    'history.viewSolution': 'ઉકેલ જુઓ',

    'solutions.title': 'રોગ ઉકેલો',
    'solutions.subtitle': 'પાક રોગો, સારવારો અને નિવારણ પદ્ધતિઓનો વ્યાપક ડેટાબેઝ.',
    'solutions.searchPlaceholder': 'રોગ અથવા પાક શોધો...',
    'solutions.allCrops': 'બધા પાક',
    'solutions.emptyTitle': 'કોઈ રોગ મળ્યો નથી',
    'solutions.emptyDesc': 'કોઈ અલગ શોધ શબ્દ અજમાવો.',
    'solutions.symptoms': 'લક્ષણો',
    'solutions.treatment': 'સારવાર',
    'solutions.prevention': 'નિવારણ',
    'solutions.viewDetails': 'સંપૂર્ણ વિગતો જુઓ →',

    'detail.backToSolutions': '← સોલ્યુશન્સ પર પાછા',
    'detail.symptoms': '📋 લક્ષણો',
    'detail.causes': '🔬 કારણો',
    'detail.chemicalTreatment': '💊 રાસાયણિક સારવાર',
    'detail.organicTreatment': '🌿 કાર્બનિક સારવાર',
    'detail.prevention': '🛡️ નિવારણ',
    'detail.recommendedTreatment': '⚕️ ભલામણ કરેલ સારવાર',
    'detail.cta': 'તમારા પાકમાં આ રોગ જોવા મળ્યો?',
    'detail.scanNow': 'તમારો પાક હમણાં સ્કેન કરો',
    'detail.notFound': 'રોગ મળ્યો નથી',

    // Severity
    'severity.high': 'ઉચ્ચ',
    'severity.critical': 'ગંભીર',
    'severity.medium': 'મધ્યમ',

    // Disease data
    'detail.affects': 'અસરગ્રસ્ત:',

    'disease.1.name': 'અર્લી બ્લાઈટ',
    'disease.1.crop': 'ટામેટા, બટાકા',
    'disease.1.symptoms': 'પાંદડા પર કેન્દ્રિત રિંગ્સ સાથે ઘેરા ડાઘ, આસપાસના પેશીઓનું પીળું પડવું, ગંભીર કિસ્સામાં પાંદડા ખરી જવા.',
    'disease.1.treatment': 'દર 7-10 દિવસે ક્લોરોથાલોનિલ અથવા મેન્કોઝેબ સ્પ્રે કરો. ઓર્ગેનિક વિકલ્પ તરીકે કોપર-આધારિત ફૂગનાશકોનો ઉપયોગ કરો.',
    'disease.1.prevention': 'બિન-સોલેનેસિયસ પાકો સાથે પાક પરિભ્રમણ કરો. ઉપરથી સિંચાઈ ટાળો. રોગમુક્ત બીજ અને પ્રતિરોધક જાતોનો ઉપયોગ કરો.',
    'disease.1.causes': 'ફૂગ અલ્ટરનેરિયા સોલાની, 24-30°C તાપમાન સાથે ગરમ ભેજવાળી પરિસ્થિતિઓમાં ખીલે છે.',
    'disease.1.organic': 'નીમ તેલ સ્પ્રે (5ml/L), ખાવાનો સોડા દ્રાવણ (1 ચમચી/લિ), કોપર ફૂગનાશક.',
    'disease.1.chemical': 'ક્લોરોથાલોનિલ, મેન્કોઝેબ, એઝોક્સિસ્ટ્રોબિન. લક્ષણો દેખાય ત્યારે લગાવો.',
    'disease.1.category': 'ફંગલ',

    'disease.2.name': 'લેટ બ્લાઈટ',
    'disease.2.crop': 'બટાકા, ટામેટા',
    'disease.2.symptoms': 'પાંદડા, દાંડી અને ફળો પર પાણી-પલાળેલા જખમ. ભીની સ્થિતિમાં પાંદડાની નીચે સફેદ કપાસ જેવી ફૂગ વૃદ્ધિ. ઝડપી ભૂરાપણું અને પાંદડાનું પતન.',
    'disease.2.treatment': 'સંક્રમિત છોડને તાત્કાલિક દૂર કરો અને નાશ કરો. કોપર-આધારિત ફૂગનાશક લગાવો. ગંભીર ચેપ માટે મેટાલેક્સિલ + મેન્કોઝેબનો ઉપયોગ કરો.',
    'disease.2.prevention': 'પ્રતિરોધક જાતો રોપો. યોગ્ય ડ્રેનેજ સુનિશ્ચિત કરો. ગીચ વાવેતર ટાળો. પ્રમાણિત રોગમુક્ત બીજ બટાકાનો ઉપયોગ કરો.',
    'disease.2.causes': 'ફાયટોફથોરા ઇન્ફેસ્ટન્સ, ઠંડા ભીના હવામાનમાં (10-20°C, >90% ભેજ) ઝડપથી ફેલાય છે.',
    'disease.2.organic': 'કોપર ઓક્સીક્લોરાઇડ સ્પ્રે, બોર્ડો મિશ્રણ.',
    'disease.2.chemical': 'મેટાલેક્સિલ, ડાયમેથોમોર્ફ, સાયમોક્સાનિલ + મેન્કોઝેબ.',
    'disease.2.category': 'ફંગલ',

    'disease.3.name': 'લીફ બ્લાસ્ટ',
    'disease.3.crop': 'ચોખા',
    'disease.3.symptoms': 'પાંદડા પર ન રાખોડી કેન્દ્ર અને ઘેરા ભૂરા કિનારીઓ સાથે હીરા આકારના જખમ. જખમ ભેગા થઈને પાંદડાના મૃત્યુનું કારણ બની શકે છે.',
    'disease.3.treatment': 'પ્રારંભિક લક્ષણો પર ટ્રાઇસાયક્લાઝોલ અથવા કાર્બેન્ડાઝિમ લગાવો. નેક બ્લાસ્ટ નિયંત્રણ માટે એડિફેનફોસનો ઉપયોગ કરો.',
    'disease.3.prevention': 'અતિશય નાઇટ્રોજન ફળદ્રુપતા ટાળો. શ્રેષ્ઠ જળ સ્તર જાળવો. પ્રતિરોધક જાતો રોપો. વાવણી પહેલા બીજને ફૂગનાશકોથી ઉપચાર કરો.',
    'disease.3.causes': 'ફૂગ મેગ્નાપોર્થે ઓરાઇઝી, ઉચ્ચ ભેજ, પાંદડાની ભીનાશ અને નાઇટ્રોજન-સમૃદ્ધ જમીન દ્વારા ઉત્તેજિત.',
    'disease.3.organic': 'નીમ ખોળ માટી ઉપયોગ, ટ્રાઇકોડર્મા જૈવ-નિયંત્રક એજન્ટ.',
    'disease.3.chemical': 'ટ્રાઇસાયક્લાઝોલ, કાર્બેન્ડાઝિમ, એડિફેનફોસ, આઇસોપ્રોથિયોલેન.',
    'disease.3.category': 'ફંગલ',

    'disease.4.name': 'રસ્ટ',
    'disease.4.crop': 'ઘઉં, જવ',
    'disease.4.symptoms': 'પાંદડા અને દાંડી પર નાના કાટ-રંગીના ફોલ્લા. મોસમના અંતે ફોલ્લા કાળા થઈ જાય છે. ગંભીર અસરગ્રસ્ત પાંદડા સમય પહેલા સુકાઈ જાય છે.',
    'disease.4.treatment': 'પ્રથમ સંકેત પર પ્રોપિકોનાઝોલ અથવા ટેબુકોનાઝોલ લગાવો. મેન્કોઝેબ રક્ષણાત્મક કવરેજ પ્રદાન કરે છે.',
    'disease.4.prevention': 'પ્રતિરોધક જાતો ઉગાડો. વહેલી વાવણી જોખમ ઘટાડે છે. અતિશય નાઇટ્રોજન ટાળો. સ્વયંસેવી ઘઉંના છોડ દૂર કરો.',
    'disease.4.causes': 'ફૂગ પક્સિનિયા એસપીપી, હવા દ્વારા ફેલાતા યુરેડોસ્પોર્સ.',
    'disease.4.organic': 'સલ્ફર સ્પ્રે, બેસિલસ સબટિલિસ જૈવ-ફૂગનાશક.',
    'disease.4.chemical': 'પ્રોપિકોનાઝોલ, ટેબુકોનાઝોલ, મેન્કોઝેબ, એઝોક્સિસ્ટ્રોબિન.',
    'disease.4.category': 'ફંગલ',

    'disease.5.name': 'બેક્ટેરિયલ બ્લાઈટ',
    'disease.5.crop': 'ચોખા, કપાસ',
    'disease.5.symptoms': 'પાંદડા પર પાણી-પલાળેલા જખમ લહેરિયાત કિનારીઓ સાથે પીળાથી ભૂરા થાય છે. સવારે યુવાન જખમો પર બેક્ટેરિયલ રિસાવ દેખાય છે.',
    'disease.5.treatment': 'કોપર ઓક્સીક્લોરાઇડ સ્પ્રેનો ઉપયોગ કરો. સ્ટ્રેપ્ટોમાઇસિન બીજ ઉપચાર. ખેતરોમાંથી પાણી કાઢો અને નાઇટ્રોજન ઘટાડો.',
    'disease.5.prevention': 'પ્રમાણિત રોગમુક્ત બીજનો ઉપયોગ કરો. પૂર સિંચાઈ ટાળો. પ્રતિરોધક જાતો રોપો. સંતુલિત ફળદ્રુપતા. ખેતર સ્વચ્છતા.',
    'disease.5.causes': 'જીવાણુ ઝેન્થોમોનાસ ઓરાઇઝી, ઘા/હાઇડેથોડ્સ દ્વારા પ્રવેશ કરે છે.',
    'disease.5.organic': 'કોપર ઓક્સીક્લોરાઇડ સ્પ્રે, સ્યુડોમોનાસ ફ્લોરેસેન્સ જૈવ-નિયંત્રણ.',
    'disease.5.chemical': 'સ્ટ્રેપ્ટોમાઇસિન સલ્ફેટ, કોપર ઓક્સીક્લોરાઇડ, બોર્ડો મિશ્રણ.',
    'disease.5.category': 'બેક્ટેરિયલ',

    'disease.6.name': 'પાઉડરી મિલ્ડ્યુ',
    'disease.6.crop': 'કુકુરબિટ, દ્રાક્ષ',
    'disease.6.symptoms': 'પાંદડા, દાંડી અને ફળો પર સફેદથી રાખોડી પાવડર જેવી ફૂગ વૃદ્ધિ. પાંદડા વિકૃત અને પીળા થઈ જાય છે. પ્રકાશસંશ્લેષણ ઘટે છે.',
    'disease.6.treatment': 'સલ્ફર-આધારિત ફૂગનાશક અથવા પોટેશિયમ બાયકાર્બોનેટ લગાવો. હળવા ચેપ માટે નીમ તેલનો ઉપયોગ કરો.',
    'disease.6.prevention': 'સારું હવા પરિભ્રમણ સુનિશ્ચિત કરો. ઉપરથી પાણી આપવાનું ટાળો. સંપૂર્ણ સૂર્યમાં રોપો. યોગ્ય ટ્રેલિસિંગ.',
    'disease.6.causes': 'ફૂગ એરિસિફે એસપીપી (કુકુરબિટ) / અનસિનુલા નેકેટર (દ્રાક્ષ). મધ્યમ તાપમાન (15-27°C) અને ઉચ્ચ ભેજ પસંદ કરે છે.',
    'disease.6.organic': 'સલ્ફર ધૂળ/સ્પ્રે, નીમ તેલ, પોટેશિયમ બાયકાર્બોનેટ, દૂધ સ્પ્રે (1:9).',
    'disease.6.chemical': 'માઇક્લોબ્યુટાનિલ, પ્રોપિકોનાઝોલ, ટ્રાઇફ્લોક્સિસ્ટ્રોબિન, સલ્ફર.',
    'disease.6.category': 'ફંગલ',

    'disease.7.name': 'લીફ સ્પોટ',
    'disease.7.crop': 'મગફળી, સોયાબીન',
    'disease.7.symptoms': 'પાંદડા પર પીળા પ્રભામંડળ સાથે ભૂરાથી ઘેરા ગોળાકાર ડાઘ. ડાઘ ભેગા થઈને પાંદડા ઝુલસ અને અકાળ પાંદડા ખરવાનું કારણ બને છે.',
    'disease.7.treatment': 'કાર્બેન્ડાઝિમ + મેન્કોઝેબ સંયોજન સ્પ્રે લગાવો. ક્લોરોથાલોનિલ અસરકારક નિયંત્રણ પ્રદાન કરે છે.',
    'disease.7.prevention': 'બિન-કઠોળ સાથે પાક પરિભ્રમણ. પ્રતિરોધક જાતોનો ઉપયોગ કરો. પાક કચરો દૂર કરો. બીજને ફૂગનાશકોથી ઉપચાર કરો.',
    'disease.7.causes': 'સેરકોસ્પોરા એસપીપી (પ્રારંભિક) / ફેયોઇસારિઓપ્સિસ પર્સોનાટા (મોડું). હવા અને વરસાદના છાંટાથી ફેલાય છે.',
    'disease.7.organic': 'નીમ તેલ સ્પ્રે, ટ્રાઇકોડર્મા વિરિડે જૈવ-નિયંત્રક.',
    'disease.7.chemical': 'કાર્બેન્ડાઝિમ, મેન્કોઝેબ, ક્લોરોથાલોનિલ, ટેબુકોનાઝોલ.',
    'disease.7.category': 'ફંગલ',

    'disease.8.name': 'ડાઉની મિલ્ડ્યુ',
    'disease.8.crop': 'દ્રાક્ષ, કુકુરબિટ',
    'disease.8.symptoms': 'પાંદડાની ઉપરની સપાટી પર પીળા ખૂણાવાળા ડાઘ. નીચે જાંબલી-રાખોડી રુંવાટી જેવી વૃદ્ધિ. સંક્રમિત અંકુર ઠુંઠા અને વિકૃત થઈ જાય છે.',
    'disease.8.treatment': 'મેટાલેક્સિલ + મેન્કોઝેબ અથવા ફોસેટાઇલ-એએલ લગાવો. સંક્રમિત પાંદડા દૂર કરો અને નાશ કરો.',
    'disease.8.prevention': 'પાંદડાની ભીનાશ ટાળો - ડ્રિપ સિંચાઈનો ઉપયોગ કરો. હવા ચળવળ માટે યોગ્ય ટ્રેલિસિંગ. પ્રતિરોધક જાતો રોપો.',
    'disease.8.causes': 'પ્લાસ્મોપેરા વિટિકોલા (દ્રાક્ષ) / સ્યુડોપેરોનોસ્પોરા ક્યુબેન્સિસ (કુકુરબિટ). ચેપ માટે પાંદડા પર મુક્ત પાણીની જરૂર છે.',
    'disease.8.organic': 'કોપર ઓક્સીક્લોરાઇડ, બોર્ડો મિશ્રણ, પોટેશિયમ ફોસ્ફાઇટ.',
    'disease.8.chemical': 'મેટાલેક્સિલ, મેન્કોઝેબ, ફોસેટાઇલ-એએલ, ડાયમેથોમોર્ફ, સાયમોક્સાનિલ.',
    'disease.8.category': 'ફંગલ',

    'disease.9.name': 'એન્થ્રેક્નોઝ',
    'disease.9.crop': 'મરચાં, કેરી',
    'disease.9.symptoms': 'ફળો પર ગુલાબી બીજાણુ સમૂહ સાથે ધસી ગયેલા ઘેરા જખમ. પાંદડાના ડાઘ અનિયમિત ભૂરા વિસ્તારો છે. સંગ્રહમાં ફળ સડો.',
    'disease.9.treatment': 'કોપર ઓક્સીક્લોરાઇડ અથવા કાર્બેન્ડાઝિમ સ્પ્રે લગાવો. સંક્રમિત ફળો દૂર કરો અને નાશ કરો. કેરી માટે લણણી પછી ગરમ પાણી ઉપચાર.',
    'disease.9.prevention': 'અસરગ્રસ્ત શાખાઓ કાપો. યોગ્ય બગીચા સ્વચ્છતા. ઉપરથી સિંચાઈ ટાળો. ફૂલો દરમિયાન રક્ષણાત્મક ફૂગનાશક લગાવો.',
    'disease.9.causes': 'કોલેટોટ્રાઇકમ એસપીપી. વરસાદના છાંટાથી ફેલાય છે, છોડના કચરા પર ટકી રહે છે.',
    'disease.9.organic': 'કોપર ઓક્સીક્લોરાઇડ, નીમ તેલ, ટ્રાઇકોડર્મા હાર્ઝિયાનમ.',
    'disease.9.chemical': 'કાર્બેન્ડાઝિમ, મેન્કોઝેબ, ક્લોરોથાલોનિલ, એઝોક્સિસ્ટ્રોબિન.',
    'disease.9.category': 'ફંગલ',

    'disease.10.name': 'વિલ્ટ',
    'disease.10.crop': 'ટામેટા, રીંગણ',
    'disease.10.symptoms': 'પાંદડાનું કરમાવું, દાંડીમાં વેસ્ક્યુલર વિકૃતિકરણ.',
    'disease.10.treatment': 'કાર્બેન્ડાઝિમથી માટી ભીંજવો, સંક્રમિત છોડ દૂર કરો.',
    'disease.10.prevention': 'માટી સોલરાઇઝેશન, પ્રતિરોધક રૂટસ્ટોક, પાક પરિભ્રમણ.',
    'disease.10.causes': 'માટીમાં ફંગલ અથવા બેક્ટેરિયલ પેથોજેન્સ, મૂળ દ્વારા પ્રવેશ કરે છે.',
    'disease.10.organic': 'નીમ ખોળ માટી ઉપયોગ, ટ્રાઇકોડર્મા જૈવ-નિયંત્રણ.',
    'disease.10.chemical': 'કાર્બેન્ડાઝિમ માટી ભીંજવી, કોપર ઓક્સીક્લોરાઇડ.',
    'disease.10.category': 'ફંગલ',

    'notFound.title': 'પેજ મળ્યું નથી',
    'notFound.desc': 'અરે! તમે જે પેજ શોધી રહ્યા છો તે અસ્તિત્વમાં નથી.',
    'notFound.button': 'હોમ પર પાછા જાઓ',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('smartfarm_language') || 'en';
  });

  const t = (key, ...args) => {
    let text = translations[language]?.[key] || translations['en']?.[key] || key;
    if (args.length > 0) {
      args.forEach((arg, i) => {
        text = text.replace(`{${i}}`, arg);
      });
    }
    return text;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('smartfarm_language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export default LanguageContext;
